name: GitHub Pages

on:
  push:
    paths: 
      - 'trigger_deploy.txt**'

jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest"

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm install -g postcss-cli autoprefixer
      - run: cd ec_website &&  npm ci

      - uses: actions/cache@v3
        with:
          path: /ec_website/tmp/hugo_cache
          key: ${{ runner.os }}-hugomod-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-hugomod-

      - name: Build
        # env:
          # HUGO_GOOGLEANALYTICS: ${{ secrets.GOOGLEANALYTICS }}
        run: cd ec_website && hugo --gc -v -s ./mainSite --minify --baseURL https://electoralclubtiet.github.io/ec_web/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./ec_website/mainSite/public
